In [1]:
import polars as pl
from polars import col
from investment_strategy.data.cleaner import *
from investment_strategy.signals.signal_construction import *
from investment_strategy.signals.signal_ranking import *
from investment_strategy.portfolio.weighting import *
from investment_strategy.portfolio.rebalancing import *
from investment_strategy.portfolio.valuation import *
from investment_strategy.analytics.return_metrics import *
from investment_strategy.analytics.risk_metrics import *
from investment_strategy.config.backtest_config import *
from investment_strategy.analytics.turnover_metrics import *
from investment_strategy.analytics.benchmark_metrics import *

market_data = pl.read_parquet("../data/raw/sp500_market_data.parquet")
market_data

shape: (937_089, 7)
┌────────────┬────────┬────────────┬────────────┬────────────┬────────────┬───────────┐
│ date       ┆ ticker ┆ open       ┆ high       ┆ low        ┆ close      ┆ volume    │
│ ---        ┆ ---    ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---       │
│ date       ┆ str    ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ i64       │
╞════════════╪════════╪════════════╪════════════╪════════════╪════════════╪═══════════╡
│ 2018-12-31 ┆ A      ┆ 62.795802  ┆ 63.874904  ┆ 62.795802  ┆ 63.855968  ┆ 1572100   │
│ 2018-12-31 ┆ AAPL   ┆ 37.613949  ┆ 37.810881  ┆ 37.127551  ┆ 37.42651   ┆ 140014000 │
│ 2018-12-31 ┆ ABBV   ┆ 66.040205  ┆ 67.042343  ┆ 65.773452  ┆ 66.465576  ┆ 5722100   │
│ 2018-12-31 ┆ ABNB   ┆ null       ┆ null       ┆ null       ┆ null       ┆ null      │
│ 2018-12-31 ┆ ABT    ┆ 62.168729  ┆ 63.202416  ┆ 62.090555  ┆ 62.828899  ┆ 6094300   │
│ …          ┆ …      ┆ …          ┆ …          ┆ …          ┆ …          ┆ …         │
│ 2026-05-29 ┆ XYZ    ┆ 74.970001  ┆ 76.660004  ┆ 74.195     ┆ 75.720001  ┆ 7380400   │
│ 2026-05-29 ┆ YUM    ┆ 149.229996 ┆ 150.179993 ┆ 147.339996 ┆ 147.949997 ┆ 3992700   │
│ 2026-05-29 ┆ ZBH    ┆ 81.952229  ┆ 82.979498  ┆ 81.363796  ┆ 82.111809  ┆ 3216600   │
│ 2026-05-29 ┆ ZBRA   ┆ 245.740005 ┆ 248.479996 ┆ 241.309998 ┆ 243.630005 ┆ 4608800   │
│ 2026-05-29 ┆ ZTS    ┆ 77.966507  ┆ 78.33394   ┆ 76.903914  ┆ 77.152184  ┆ 9295100   │
└────────────┴────────┴────────────┴────────────┴────────────┴────────────┴───────────┘

In [2]:
benchmark_data = pl.read_parquet("../data/raw/benchmark_market_data.parquet")
benchmark_data

shape: (9_315, 7)
┌────────────┬────────┬──────────────┬──────────────┬──────────────┬──────────────┬─────────────┐
│ date       ┆ ticker ┆ open         ┆ high         ┆ low          ┆ close        ┆ volume      │
│ ---        ┆ ---    ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---         │
│ date       ┆ str    ┆ f64          ┆ f64          ┆ f64          ┆ f64          ┆ i64         │
╞════════════╪════════╪══════════════╪══════════════╪══════════════╪══════════════╪═════════════╡
│ 2018-12-31 ┆ ^DJI   ┆ 23153.939453 ┆ 23333.179688 ┆ 23118.300781 ┆ 23327.460938 ┆ 288830000   │
│ 2018-12-31 ┆ ^GSPC  ┆ 2498.939941  ┆ 2509.23999   ┆ 2482.820068  ┆ 2506.850098  ┆ 3461920000  │
│ 2018-12-31 ┆ ^IXIC  ┆ 6649.52002   ┆ 6659.959961  ┆ 6570.060059  ┆ 6635.279785  ┆ 2109320000  │
│ 2018-12-31 ┆ ^NDX   ┆ 6354.850098  ┆ 6365.390137  ┆ 6273.939941  ┆ 6329.970215  ┆ 2109320000  │
│ 2018-12-31 ┆ ^RUT   ┆ 1338.52002   ┆ 1348.560059  ┆ 1329.170044  ┆ 1348.560059  ┆ 3461920000  │
│ …          ┆ …      ┆ …            ┆ …            ┆ …            ┆ …            ┆ …           │
│ 2026-05-29 ┆ ^DJI   ┆ 50773.910156 ┆ 51094.179688 ┆ 50698.269531 ┆ 51032.460938 ┆ 894700000   │
│ 2026-05-29 ┆ ^GSPC  ┆ 7579.330078  ┆ 7599.379883  ┆ 7563.549805  ┆ 7580.060059  ┆ 7858290000  │
│ 2026-05-29 ┆ ^IXIC  ┆ 26960.839844 ┆ 27094.800781 ┆ 26859.269531 ┆ 26972.619141 ┆ 11906000000 │
│ 2026-05-29 ┆ ^NDX   ┆ 30333.859375 ┆ 30470.029297 ┆ 30210.009766 ┆ 30333.179688 ┆ 11906000000 │
│ 2026-05-29 ┆ ^RUT   ┆ 2932.570068  ┆ 2932.570068  ┆ 2898.830078  ┆ 2919.340088  ┆ 7858290000  │
└────────────┴────────┴──────────────┴──────────────┴──────────────┴──────────────┴─────────────┘

# Signal Construction

In [3]:
market_data = fill_OHLCV_missing_values(market_data)
close_price = market_data.select(
    col("date"),
    col("ticker"),
    col("close")
)

In [4]:
end_date = get_backtest_end_date(
    backtest_start_date=BACKTEST_START_DATE,
    backtest_period=BACKTEST_PERIOD,
    backtest_period_unit=BACKTEST_PERIOD_UNIT,
)
end_date

datetime.date(2024, 12, 31)

In [5]:
trading_calendar = get_trading_calendar(cleaned_close_prices_dataset=close_price)
trading_calendar

shape: (1_863, 1)
┌────────────┐
│ date       │
│ ---        │
│ date       │
╞════════════╡
│ 2018-12-31 │
│ 2019-01-02 │
│ 2019-01-03 │
│ 2019-01-04 │
│ 2019-01-07 │
│ …          │
│ 2026-05-22 │
│ 2026-05-26 │
│ 2026-05-27 │
│ 2026-05-28 │
│ 2026-05-29 │
└────────────┘

In [6]:
date_mapping_df = create_date_mapping(
    trading_calendar=trading_calendar,
    rebalance_frequency=REBALANCE_FREQUENCY,
    rebalance_freq_unit=REBALANCE_FREQ_UNIT,
    backtest_start_date=BACKTEST_START_DATE,
    backtest_end_date=end_date,
    lookback_period_for_total_returns=LOOKBACK_PERIOD,
    lookback_period_unit=LOOKBACK_PERIOD_UNIT,
)
date_mapping_df

shape: (19, 4)
┌───────────────┬───────────────┬─────────────┬────────────────┐
│ lookback_date ┆ lag_base_date ┆ signal_date ┆ rebalance_date │
│ ---           ┆ ---           ┆ ---         ┆ ---            │
│ date          ┆ date          ┆ date        ┆ date           │
╞═══════════════╪═══════════════╪═════════════╪════════════════╡
│ 2021-06-30    ┆ 2021-11-30    ┆ 2021-12-30  ┆ 2021-12-31     │
│ 2021-08-25    ┆ 2022-01-25    ┆ 2022-02-25  ┆ 2022-02-28     │
│ 2021-10-29    ┆ 2022-03-29    ┆ 2022-04-29  ┆ 2022-05-02     │
│ 2021-12-29    ┆ 2022-05-27    ┆ 2022-06-29  ┆ 2022-06-30     │
│ 2022-02-28    ┆ 2022-07-29    ┆ 2022-08-30  ┆ 2022-08-31     │
│ …             ┆ …             ┆ …           ┆ …              │
│ 2023-10-27    ┆ 2024-03-28    ┆ 2024-04-29  ┆ 2024-04-30     │
│ 2023-12-28    ┆ 2024-05-28    ┆ 2024-06-28  ┆ 2024-07-01     │
│ 2024-02-29    ┆ 2024-07-30    ┆ 2024-08-30  ┆ 2024-09-03     │
│ 2024-04-30    ┆ 2024-09-30    ┆ 2024-10-30  ┆ 2024-10-31     │
│ 2024-06-28    ┆ 2024-11-29    ┆ 2024-12-30  ┆ 2024-12-31     │
└───────────────┴───────────────┴─────────────┴────────────────┘

In [7]:
price_date_df = get_prices_for_date_mapping(
    cleaned_close_prices_dataset=close_price,
    cleaned_stock_OHLCV=market_data,
    date_mapping_df=date_mapping_df,
)
price_date_df

shape: (9_557, 9)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ signal_dat ┆ ticker ┆ signal_clo ┆ lookback_ ┆ … ┆ rebalance ┆ lookback_ ┆ lag_base_ ┆ rebalance │
│ e          ┆ ---    ┆ se         ┆ date      ┆   ┆ _date     ┆ close     ┆ close     ┆ _open     │
│ ---        ┆ str    ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ date       ┆        ┆ f64        ┆ date      ┆   ┆ date      ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2021-12-30 ┆ A      ┆ 155.463638 ┆ 2021-06-3 ┆ … ┆ 2021-12-3 ┆ 142.46871 ┆ 145.81959 ┆ 154.95148 │
│            ┆        ┆            ┆ 0         ┆   ┆ 1         ┆ 9         ┆ 5         ┆ 4         │
│ 2021-12-30 ┆ AAPL   ┆ 174.214935 ┆ 2021-06-3 ┆ … ┆ 2021-12-3 ┆ 133.50204 ┆ 161.60340 ┆ 174.10737 │
│            ┆        ┆            ┆ 0         ┆   ┆ 1         ┆ 5         ┆ 9         ┆ 5         │
│ 2021-12-30 ┆ ABBV   ┆ 114.511681 ┆ 2021-06-3 ┆ … ┆ 2021-12-3 ┆ 92.721123 ┆ 97.115463 ┆ 114.60431 │
│            ┆        ┆            ┆ 0         ┆   ┆ 1         ┆           ┆           ┆           │
│ 2021-12-30 ┆ ABNB   ┆ 168.779999 ┆ 2021-06-3 ┆ … ┆ 2021-12-3 ┆ 153.13999 ┆ 172.53999 ┆ 168.77999 │
│            ┆        ┆            ┆ 0         ┆   ┆ 1         ┆ 9         ┆ 3         ┆ 9         │
│ 2021-12-30 ┆ ABT    ┆ 128.427795 ┆ 2021-06-3 ┆ … ┆ 2021-12-3 ┆ 104.78808 ┆ 114.55578 ┆ 128.42782 │
│            ┆        ┆            ┆ 0         ┆   ┆ 1         ┆ 6         ┆ 6         ┆ 2         │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2024-12-30 ┆ XYZ    ┆ 87.480003  ┆ 2024-06-2 ┆ … ┆ 2024-12-3 ┆ 64.489998 ┆ 88.550003 ┆ 87.720001 │
│            ┆        ┆            ┆ 8         ┆   ┆ 1         ┆           ┆           ┆           │
│ 2024-12-30 ┆ YUM    ┆ 129.748352 ┆ 2024-06-2 ┆ … ┆ 2024-12-3 ┆ 127.46157 ┆ 134.36413 ┆ 130.30221 │
│            ┆        ┆            ┆ 8         ┆   ┆ 1         ┆ 8         ┆ 6         ┆           │
│ 2024-12-30 ┆ ZBH    ┆ 103.810539 ┆ 2024-06-2 ┆ … ┆ 2024-12-3 ┆ 106.41676 ┆ 110.16154 ┆ 104.31284 │
│            ┆        ┆            ┆ 8         ┆   ┆ 1         ┆ 3         ┆ 5         ┆ 7         │
│ 2024-12-30 ┆ ZBRA   ┆ 383.850006 ┆ 2024-06-2 ┆ … ┆ 2024-12-3 ┆ 308.92999 ┆ 407.0     ┆ 383.42001 │
│            ┆        ┆            ┆ 8         ┆   ┆ 1         ┆ 3         ┆           ┆ 3         │
│ 2024-12-30 ┆ ZTS    ┆ 157.64212  ┆ 2024-06-2 ┆ … ┆ 2024-12-3 ┆ 167.64997 ┆ 170.28340 ┆ 158.28339 │
│            ┆        ┆            ┆ 8         ┆   ┆ 1         ┆ 9         ┆ 1         ┆ 7         │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:
past_returns = calculate_momentum(
    factor_reference_table=price_date_df,
    lookback_period_for_total_returns=LOOKBACK_PERIOD,
    lookback_period_unit=LOOKBACK_PERIOD_UNIT,
)
past_returns

shape: (9_557, 10)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ signal_dat ┆ ticker ┆ signal_clo ┆ lookback_ ┆ … ┆ lookback_ ┆ lag_base_ ┆ rebalance ┆ momentum_ │
│ e          ┆ ---    ┆ se         ┆ date      ┆   ┆ close     ┆ close     ┆ _open     ┆ 6mo       │
│ ---        ┆ str    ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ date       ┆        ┆ f64        ┆ date      ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2021-12-30 ┆ A      ┆ 155.463638 ┆ 2021-06-3 ┆ … ┆ 142.46871 ┆ 145.81959 ┆ 154.95148 ┆ 0.02352   │
│            ┆        ┆            ┆ 0         ┆   ┆ 9         ┆ 5         ┆ 4         ┆           │
│ 2021-12-30 ┆ AAPL   ┆ 174.214935 ┆ 2021-06-3 ┆ … ┆ 133.50204 ┆ 161.60340 ┆ 174.10737 ┆ 0.210494  │
│            ┆        ┆            ┆ 0         ┆   ┆ 5         ┆ 9         ┆ 5         ┆           │
│ 2021-12-30 ┆ ABBV   ┆ 114.511681 ┆ 2021-06-3 ┆ … ┆ 92.721123 ┆ 97.115463 ┆ 114.60431 ┆ 0.047393  │
│            ┆        ┆            ┆ 0         ┆   ┆           ┆           ┆           ┆           │
│ 2021-12-30 ┆ ABNB   ┆ 168.779999 ┆ 2021-06-3 ┆ … ┆ 153.13999 ┆ 172.53999 ┆ 168.77999 ┆ 0.126681  │
│            ┆        ┆            ┆ 0         ┆   ┆ 9         ┆ 3         ┆ 9         ┆           │
│ 2021-12-30 ┆ ABT    ┆ 128.427795 ┆ 2021-06-3 ┆ … ┆ 104.78808 ┆ 114.55578 ┆ 128.42782 ┆ 0.093214  │
│            ┆        ┆            ┆ 0         ┆   ┆ 6         ┆ 6         ┆ 2         ┆           │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2024-12-30 ┆ XYZ    ┆ 87.480003  ┆ 2024-06-2 ┆ … ┆ 64.489998 ┆ 88.550003 ┆ 87.720001 ┆ 0.373081  │
│            ┆        ┆            ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│ 2024-12-30 ┆ YUM    ┆ 129.748352 ┆ 2024-06-2 ┆ … ┆ 127.46157 ┆ 134.36413 ┆ 130.30221 ┆ 0.054154  │
│            ┆        ┆            ┆ 8         ┆   ┆ 8         ┆ 6         ┆           ┆           │
│ 2024-12-30 ┆ ZBH    ┆ 103.810539 ┆ 2024-06-2 ┆ … ┆ 106.41676 ┆ 110.16154 ┆ 104.31284 ┆ 0.03519   │
│            ┆        ┆            ┆ 8         ┆   ┆ 3         ┆ 5         ┆ 7         ┆           │
│ 2024-12-30 ┆ ZBRA   ┆ 383.850006 ┆ 2024-06-2 ┆ … ┆ 308.92999 ┆ 407.0     ┆ 383.42001 ┆ 0.317451  │
│            ┆        ┆            ┆ 8         ┆   ┆ 3         ┆           ┆ 3         ┆           │
│ 2024-12-30 ┆ ZTS    ┆ 157.64212  ┆ 2024-06-2 ┆ … ┆ 167.64997 ┆ 170.28340 ┆ 158.28339 ┆ 0.015708  │
│            ┆        ┆            ┆ 8         ┆   ┆ 9         ┆ 1         ┆ 7         ┆           │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [9]:
past_std = calculate_past_returns_std(
    cleaned_close_prices_dataset=close_price,
    factor_reference_table=past_returns,
    date_mapping_df=date_mapping_df,
    lookback_period_for_total_returns=LOOKBACK_PERIOD,
    lookback_period_unit=LOOKBACK_PERIOD_UNIT,
)
past_std

shape: (9_557, 11)
┌────────────┬────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ signal_dat ┆ ticker ┆ signal_clo ┆ lookback_d ┆ … ┆ lag_base_ ┆ rebalance ┆ momentum_ ┆ vol_6mo  │
│ e          ┆ ---    ┆ se         ┆ ate        ┆   ┆ close     ┆ _open     ┆ 6mo       ┆ ---      │
│ ---        ┆ str    ┆ ---        ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64      │
│ date       ┆        ┆ f64        ┆ date       ┆   ┆ f64       ┆ f64       ┆ f64       ┆          │
╞════════════╪════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2021-12-30 ┆ A      ┆ 155.463638 ┆ 2021-06-30 ┆ … ┆ 145.81959 ┆ 154.95148 ┆ 0.02352   ┆ 0.01249  │
│            ┆        ┆            ┆            ┆   ┆ 5         ┆ 4         ┆           ┆          │
│ 2021-12-30 ┆ AAPL   ┆ 174.214935 ┆ 2021-06-30 ┆ … ┆ 161.60340 ┆ 174.10737 ┆ 0.210494  ┆ 0.013089 │
│            ┆        ┆            ┆            ┆   ┆ 9         ┆ 5         ┆           ┆          │
│ 2021-12-30 ┆ ABBV   ┆ 114.511681 ┆ 2021-06-30 ┆ … ┆ 97.115463 ┆ 114.60431 ┆ 0.047393  ┆ 0.012661 │
│ 2021-12-30 ┆ ABNB   ┆ 168.779999 ┆ 2021-06-30 ┆ … ┆ 172.53999 ┆ 168.77999 ┆ 0.126681  ┆ 0.027615 │
│            ┆        ┆            ┆            ┆   ┆ 3         ┆ 9         ┆           ┆          │
│ 2021-12-30 ┆ ABT    ┆ 128.427795 ┆ 2021-06-30 ┆ … ┆ 114.55578 ┆ 128.42782 ┆ 0.093214  ┆ 0.010467 │
│            ┆        ┆            ┆            ┆   ┆ 6         ┆ 2         ┆           ┆          │
│ …          ┆ …      ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2024-12-30 ┆ XYZ    ┆ 87.480003  ┆ 2024-06-28 ┆ … ┆ 88.550003 ┆ 87.720001 ┆ 0.373081  ┆ 0.027146 │
│ 2024-12-30 ┆ YUM    ┆ 129.748352 ┆ 2024-06-28 ┆ … ┆ 134.36413 ┆ 130.30221 ┆ 0.054154  ┆ 0.010647 │
│            ┆        ┆            ┆            ┆   ┆ 6         ┆           ┆           ┆          │
│ 2024-12-30 ┆ ZBH    ┆ 103.810539 ┆ 2024-06-28 ┆ … ┆ 110.16154 ┆ 104.31284 ┆ 0.03519   ┆ 0.015842 │
│            ┆        ┆            ┆            ┆   ┆ 5         ┆ 7         ┆           ┆          │
│ 2024-12-30 ┆ ZBRA   ┆ 383.850006 ┆ 2024-06-28 ┆ … ┆ 407.0     ┆ 383.42001 ┆ 0.317451  ┆ 0.016841 │
│            ┆        ┆            ┆            ┆   ┆           ┆ 3         ┆           ┆          │
│ 2024-12-30 ┆ ZTS    ┆ 157.64212  ┆ 2024-06-28 ┆ … ┆ 170.28340 ┆ 158.28339 ┆ 0.015708  ┆ 0.013769 │
│            ┆        ┆            ┆            ┆   ┆ 1         ┆ 7         ┆           ┆          │
└────────────┴────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
risk_adjusted_table = get_risk_adjusted_return(
    factor_reference_with_momentum_and_vol=past_std,
    lookback_period_for_total_returns=LOOKBACK_PERIOD,
    lookback_period_unit=LOOKBACK_PERIOD_UNIT,
)
risk_adjusted_table

shape: (9_557, 12)
┌────────────┬────────┬────────────┬────────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ signal_dat ┆ ticker ┆ signal_clo ┆ lookback_d ┆ … ┆ rebalance ┆ momentum_ ┆ vol_6mo  ┆ risk_adju │
│ e          ┆ ---    ┆ se         ┆ ate        ┆   ┆ _open     ┆ 6mo       ┆ ---      ┆ sted_mome │
│ ---        ┆ str    ┆ ---        ┆ ---        ┆   ┆ ---       ┆ ---       ┆ f64      ┆ ntum_6mo  │
│ date       ┆        ┆ f64        ┆ date       ┆   ┆ f64       ┆ f64       ┆          ┆ ---       │
│            ┆        ┆            ┆            ┆   ┆           ┆           ┆          ┆ f64       │
╞════════════╪════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ 2021-12-30 ┆ A      ┆ 155.463638 ┆ 2021-06-30 ┆ … ┆ 154.95148 ┆ 0.02352   ┆ 0.01249  ┆ 1.883082  │
│            ┆        ┆            ┆            ┆   ┆ 4         ┆           ┆          ┆           │
│ 2021-12-30 ┆ AAPL   ┆ 174.214935 ┆ 2021-06-30 ┆ … ┆ 174.10737 ┆ 0.210494  ┆ 0.013089 ┆ 16.081247 │
│            ┆        ┆            ┆            ┆   ┆ 5         ┆           ┆          ┆           │
│ 2021-12-30 ┆ ABBV   ┆ 114.511681 ┆ 2021-06-30 ┆ … ┆ 114.60431 ┆ 0.047393  ┆ 0.012661 ┆ 3.743267  │
│ 2021-12-30 ┆ ABNB   ┆ 168.779999 ┆ 2021-06-30 ┆ … ┆ 168.77999 ┆ 0.126681  ┆ 0.027615 ┆ 4.587432  │
│            ┆        ┆            ┆            ┆   ┆ 9         ┆           ┆          ┆           │
│ 2021-12-30 ┆ ABT    ┆ 128.427795 ┆ 2021-06-30 ┆ … ┆ 128.42782 ┆ 0.093214  ┆ 0.010467 ┆ 8.905733  │
│            ┆        ┆            ┆            ┆   ┆ 2         ┆           ┆          ┆           │
│ …          ┆ …      ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ 2024-12-30 ┆ XYZ    ┆ 87.480003  ┆ 2024-06-28 ┆ … ┆ 87.720001 ┆ 0.373081  ┆ 0.027146 ┆ 13.743568 │
│ 2024-12-30 ┆ YUM    ┆ 129.748352 ┆ 2024-06-28 ┆ … ┆ 130.30221 ┆ 0.054154  ┆ 0.010647 ┆ 5.086498  │
│ 2024-12-30 ┆ ZBH    ┆ 103.810539 ┆ 2024-06-28 ┆ … ┆ 104.31284 ┆ 0.03519   ┆ 0.015842 ┆ 2.221282  │
│            ┆        ┆            ┆            ┆   ┆ 7         ┆           ┆          ┆           │
│ 2024-12-30 ┆ ZBRA   ┆ 383.850006 ┆ 2024-06-28 ┆ … ┆ 383.42001 ┆ 0.317451  ┆ 0.016841 ┆ 18.849365 │
│            ┆        ┆            ┆            ┆   ┆ 3         ┆           ┆          ┆           │
│ 2024-12-30 ┆ ZTS    ┆ 157.64212  ┆ 2024-06-28 ┆ … ┆ 158.28339 ┆ 0.015708  ┆ 0.013769 ┆ 1.140791  │
│            ┆        ┆            ┆            ┆   ┆ 7         ┆           ┆          ┆           │
└────────────┴────────┴────────────┴────────────┴───┴───────────┴───────────┴──────────┴───────────┘

# Signal Ranking

In [11]:
signal_ranked = rank_signal(
    signal_df=risk_adjusted_table,
    signal_col=f"risk_adjusted_momentum_{LOOKBACK_PERIOD}{LOOKBACK_PERIOD_UNIT}",
)
signal_ranked

shape: (9_557, 13)
┌────────────┬────────┬────────────┬────────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ signal_dat ┆ ticker ┆ signal_clo ┆ lookback_d ┆ … ┆ momentum_ ┆ vol_6mo  ┆ risk_adju ┆ risk_adju │
│ e          ┆ ---    ┆ se         ┆ ate        ┆   ┆ 6mo       ┆ ---      ┆ sted_mome ┆ sted_mome │
│ ---        ┆ str    ┆ ---        ┆ ---        ┆   ┆ ---       ┆ f64      ┆ ntum_6mo  ┆ ntum_6mo  │
│ date       ┆        ┆ f64        ┆ date       ┆   ┆ f64       ┆          ┆ ---       ┆ ran…      │
│            ┆        ┆            ┆            ┆   ┆           ┆          ┆ f64       ┆ ---       │
│            ┆        ┆            ┆            ┆   ┆           ┆          ┆           ┆ u32       │
╞════════════╪════════╪════════════╪════════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 2021-12-30 ┆ A      ┆ 155.463638 ┆ 2021-06-30 ┆ … ┆ 0.02352   ┆ 0.01249  ┆ 1.883082  ┆ 255       │
│ 2021-12-30 ┆ AAPL   ┆ 174.214935 ┆ 2021-06-30 ┆ … ┆ 0.210494  ┆ 0.013089 ┆ 16.081247 ┆ 42        │
│ 2021-12-30 ┆ ABBV   ┆ 114.511681 ┆ 2021-06-30 ┆ … ┆ 0.047393  ┆ 0.012661 ┆ 3.743267  ┆ 213       │
│ 2021-12-30 ┆ ABNB   ┆ 168.779999 ┆ 2021-06-30 ┆ … ┆ 0.126681  ┆ 0.027615 ┆ 4.587432  ┆ 195       │
│ 2021-12-30 ┆ ABT    ┆ 128.427795 ┆ 2021-06-30 ┆ … ┆ 0.093214  ┆ 0.010467 ┆ 8.905733  ┆ 111       │
│ …          ┆ …      ┆ …          ┆ …          ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ 2024-12-30 ┆ XYZ    ┆ 87.480003  ┆ 2024-06-28 ┆ … ┆ 0.373081  ┆ 0.027146 ┆ 13.743568 ┆ 191       │
│ 2024-12-30 ┆ YUM    ┆ 129.748352 ┆ 2024-06-28 ┆ … ┆ 0.054154  ┆ 0.010647 ┆ 5.086498  ┆ 341       │
│ 2024-12-30 ┆ ZBH    ┆ 103.810539 ┆ 2024-06-28 ┆ … ┆ 0.03519   ┆ 0.015842 ┆ 2.221282  ┆ 376       │
│ 2024-12-30 ┆ ZBRA   ┆ 383.850006 ┆ 2024-06-28 ┆ … ┆ 0.317451  ┆ 0.016841 ┆ 18.849365 ┆ 112       │
│ 2024-12-30 ┆ ZTS    ┆ 157.64212  ┆ 2024-06-28 ┆ … ┆ 0.015708  ┆ 0.013769 ┆ 1.140791  ┆ 388       │
└────────────┴────────┴────────────┴────────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [12]:
filtered_ticker = filter_top_ranked(
    ranked_signal_df=signal_ranked,
    rank_col=f"risk_adjusted_momentum_{LOOKBACK_PERIOD}{LOOKBACK_PERIOD_UNIT} rank",
    top_n=TOP_N,
)
filtered_ticker

shape: (190, 13)
┌────────────┬────────┬────────────┬────────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ signal_dat ┆ ticker ┆ signal_clo ┆ lookback_d ┆ … ┆ momentum_ ┆ vol_6mo  ┆ risk_adju ┆ risk_adju │
│ e          ┆ ---    ┆ se         ┆ ate        ┆   ┆ 6mo       ┆ ---      ┆ sted_mome ┆ sted_mome │
│ ---        ┆ str    ┆ ---        ┆ ---        ┆   ┆ ---       ┆ f64      ┆ ntum_6mo  ┆ ntum_6mo  │
│ date       ┆        ┆ f64        ┆ date       ┆   ┆ f64       ┆          ┆ ---       ┆ ran…      │
│            ┆        ┆            ┆            ┆   ┆           ┆          ┆ f64       ┆ ---       │
│            ┆        ┆            ┆            ┆   ┆           ┆          ┆           ┆ u32       │
╞════════════╪════════╪════════════╪════════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 2021-12-30 ┆ ALB    ┆ 221.557343 ┆ 2021-06-30 ┆ … ┆ 0.584559  ┆ 0.02389  ┆ 24.468939 ┆ 10        │
│ 2021-12-30 ┆ AMD    ┆ 145.149994 ┆ 2021-06-30 ┆ … ┆ 0.686043  ┆ 0.025971 ┆ 26.415665 ┆ 8         │
│ 2021-12-30 ┆ BLDR   ┆ 84.050003  ┆ 2021-06-30 ┆ … ┆ 0.627754  ┆ 0.020418 ┆ 30.7454   ┆ 3         │
│ 2021-12-30 ┆ COST   ┆ 535.266479 ┆ 2021-06-30 ┆ … ┆ 0.367971  ┆ 0.010224 ┆ 35.990245 ┆ 2         │
│ 2021-12-30 ┆ DDOG   ┆ 178.929993 ┆ 2021-06-30 ┆ … ┆ 0.713009  ┆ 0.026257 ┆ 27.15499  ┆ 6         │
│ …          ┆ …      ┆ …          ┆ …          ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ 2024-12-30 ┆ NI     ┆ 35.226597  ┆ 2024-06-28 ┆ … ┆ 0.34349   ┆ 0.009243 ┆ 37.160354 ┆ 5         │
│ 2024-12-30 ┆ PLTR   ┆ 77.18      ┆ 2024-06-28 ┆ … ┆ 1.648243  ┆ 0.037635 ┆ 43.795033 ┆ 3         │
│ 2024-12-30 ┆ TPL    ┆ 365.909271 ┆ 2024-06-28 ┆ … ┆ 1.212224  ┆ 0.026436 ┆ 45.855291 ┆ 2         │
│ 2024-12-30 ┆ TRGP   ┆ 172.180573 ┆ 2024-06-28 ┆ … ┆ 0.60256   ┆ 0.016254 ┆ 37.070911 ┆ 6         │
│ 2024-12-30 ┆ UAL    ┆ 98.209999  ┆ 2024-06-28 ┆ … ┆ 0.98993   ┆ 0.028557 ┆ 34.665381 ┆ 10        │
└────────────┴────────┴────────────┴────────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [13]:
sorted_ranking = sort_rankings(
    filtered_signal_df=filtered_ticker,
    rank_col=f"risk_adjusted_momentum_{LOOKBACK_PERIOD}{LOOKBACK_PERIOD_UNIT} rank",
)
sorted_ranking

shape: (190, 13)
┌────────────┬────────┬────────────┬────────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ signal_dat ┆ ticker ┆ signal_clo ┆ lookback_d ┆ … ┆ momentum_ ┆ vol_6mo  ┆ risk_adju ┆ risk_adju │
│ e          ┆ ---    ┆ se         ┆ ate        ┆   ┆ 6mo       ┆ ---      ┆ sted_mome ┆ sted_mome │
│ ---        ┆ str    ┆ ---        ┆ ---        ┆   ┆ ---       ┆ f64      ┆ ntum_6mo  ┆ ntum_6mo  │
│ date       ┆        ┆ f64        ┆ date       ┆   ┆ f64       ┆          ┆ ---       ┆ ran…      │
│            ┆        ┆            ┆            ┆   ┆           ┆          ┆ f64       ┆ ---       │
│            ┆        ┆            ┆            ┆   ┆           ┆          ┆           ┆ u32       │
╞════════════╪════════╪════════════╪════════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 2021-12-30 ┆ FDS    ┆ 461.847412 ┆ 2021-06-30 ┆ … ┆ 0.401728  ┆ 0.010503 ┆ 38.250071 ┆ 1         │
│ 2021-12-30 ┆ COST   ┆ 535.266479 ┆ 2021-06-30 ┆ … ┆ 0.367971  ┆ 0.010224 ┆ 35.990245 ┆ 2         │
│ 2021-12-30 ┆ BLDR   ┆ 84.050003  ┆ 2021-06-30 ┆ … ┆ 0.627754  ┆ 0.020418 ┆ 30.7454   ┆ 3         │
│ 2021-12-30 ┆ VRSK   ┆ 221.089966 ┆ 2021-06-30 ┆ … ┆ 0.288854  ┆ 0.009398 ┆ 30.735613 ┆ 4         │
│ 2021-12-30 ┆ ODFL   ┆ 173.97641  ┆ 2021-06-30 ┆ … ┆ 0.401147  ┆ 0.013245 ┆ 30.28613  ┆ 5         │
│ …          ┆ …      ┆ …          ┆ …          ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ 2024-12-30 ┆ TRGP   ┆ 172.180573 ┆ 2024-06-28 ┆ … ┆ 0.60256   ┆ 0.016254 ┆ 37.070911 ┆ 6         │
│ 2024-12-30 ┆ ATO    ┆ 134.360123 ┆ 2024-06-28 ┆ … ┆ 0.312903  ┆ 0.008631 ┆ 36.252237 ┆ 7         │
│ 2024-12-30 ┆ AXON   ┆ 604.320007 ┆ 2024-06-28 ┆ … ┆ 1.198749  ┆ 0.033564 ┆ 35.715292 ┆ 8         │
│ 2024-12-30 ┆ KMI    ┆ 25.715519  ┆ 2024-06-28 ┆ … ┆ 0.45878   ┆ 0.012947 ┆ 35.434261 ┆ 9         │
│ 2024-12-30 ┆ UAL    ┆ 98.209999  ┆ 2024-06-28 ┆ … ┆ 0.98993   ┆ 0.028557 ┆ 34.665381 ┆ 10        │
└────────────┴────────┴────────────┴────────────┴───┴───────────┴──────────┴───────────┴───────────┘

# Portfolio Weights

In [14]:
equal_weighted_portfolio = construct_portfolio_weights(
    filtered_signal_df=filtered_ticker, weighting_method="equal_weighted"
)
equal_weighted_portfolio

shape: (190, 14)
┌────────────┬────────┬────────────┬────────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ signal_dat ┆ ticker ┆ signal_clo ┆ lookback_d ┆ … ┆ vol_6mo  ┆ risk_adju ┆ risk_adju ┆ portfolio │
│ e          ┆ ---    ┆ se         ┆ ate        ┆   ┆ ---      ┆ sted_mome ┆ sted_mome ┆ _weight   │
│ ---        ┆ str    ┆ ---        ┆ ---        ┆   ┆ f64      ┆ ntum_6mo  ┆ ntum_6mo  ┆ ---       │
│ date       ┆        ┆ f64        ┆ date       ┆   ┆          ┆ ---       ┆ ran…      ┆ f64       │
│            ┆        ┆            ┆            ┆   ┆          ┆ f64       ┆ ---       ┆           │
│            ┆        ┆            ┆            ┆   ┆          ┆           ┆ u32       ┆           │
╞════════════╪════════╪════════════╪════════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ 2021-12-30 ┆ ALB    ┆ 221.557343 ┆ 2021-06-30 ┆ … ┆ 0.02389  ┆ 24.468939 ┆ 10        ┆ 0.1       │
│ 2021-12-30 ┆ AMD    ┆ 145.149994 ┆ 2021-06-30 ┆ … ┆ 0.025971 ┆ 26.415665 ┆ 8         ┆ 0.1       │
│ 2021-12-30 ┆ BLDR   ┆ 84.050003  ┆ 2021-06-30 ┆ … ┆ 0.020418 ┆ 30.7454   ┆ 3         ┆ 0.1       │
│ 2021-12-30 ┆ COST   ┆ 535.266479 ┆ 2021-06-30 ┆ … ┆ 0.010224 ┆ 35.990245 ┆ 2         ┆ 0.1       │
│ 2021-12-30 ┆ DDOG   ┆ 178.929993 ┆ 2021-06-30 ┆ … ┆ 0.026257 ┆ 27.15499  ┆ 6         ┆ 0.1       │
│ …          ┆ …      ┆ …          ┆ …          ┆ … ┆ …        ┆ …         ┆ …         ┆ …         │
│ 2024-12-30 ┆ NI     ┆ 35.226597  ┆ 2024-06-28 ┆ … ┆ 0.009243 ┆ 37.160354 ┆ 5         ┆ 0.1       │
│ 2024-12-30 ┆ PLTR   ┆ 77.18      ┆ 2024-06-28 ┆ … ┆ 0.037635 ┆ 43.795033 ┆ 3         ┆ 0.1       │
│ 2024-12-30 ┆ TPL    ┆ 365.909271 ┆ 2024-06-28 ┆ … ┆ 0.026436 ┆ 45.855291 ┆ 2         ┆ 0.1       │
│ 2024-12-30 ┆ TRGP   ┆ 172.180573 ┆ 2024-06-28 ┆ … ┆ 0.016254 ┆ 37.070911 ┆ 6         ┆ 0.1       │
│ 2024-12-30 ┆ UAL    ┆ 98.209999  ┆ 2024-06-28 ┆ … ┆ 0.028557 ┆ 34.665381 ┆ 10        ┆ 0.1       │
└────────────┴────────┴────────────┴────────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [15]:
rebalance_allocation_df = prepare_rebalance_allocation_df(
    weighted_portfolio_signal_df=equal_weighted_portfolio
)
rebalance_allocation_df

shape: (190, 4)
┌────────────────┬────────┬────────────────┬──────────────────┐
│ rebalance_date ┆ ticker ┆ rebalance_open ┆ portfolio_weight │
│ ---            ┆ ---    ┆ ---            ┆ ---              │
│ date           ┆ str    ┆ f64            ┆ f64              │
╞════════════════╪════════╪════════════════╪══════════════════╡
│ 2021-12-31     ┆ ALB    ┆ 221.235862     ┆ 0.1              │
│ 2021-12-31     ┆ AMD    ┆ 146.160004     ┆ 0.1              │
│ 2021-12-31     ┆ BLDR   ┆ 84.290001      ┆ 0.1              │
│ 2021-12-31     ┆ COST   ┆ 534.791945     ┆ 0.1              │
│ 2021-12-31     ┆ DDOG   ┆ 179.190002     ┆ 0.1              │
│ …              ┆ …      ┆ …              ┆ …                │
│ 2024-12-31     ┆ NI     ┆ 35.274594      ┆ 0.1              │
│ 2024-12-31     ┆ PLTR   ┆ 77.580002      ┆ 0.1              │
│ 2024-12-31     ┆ TPL    ┆ 367.419189     ┆ 0.1              │
│ 2024-12-31     ┆ TRGP   ┆ 172.538972     ┆ 0.1              │
│ 2024-12-31     ┆ UAL    ┆ 97.82          ┆ 0.1              │
└────────────────┴────────┴────────────────┴──────────────────┘

In [16]:
rebalance_date = date_mapping_df.get_column("rebalance_date")
rebalance_date

shape: (19,)
Series: 'rebalance_date' [date]
[
	2021-12-31
	2022-02-28
	2022-05-02
	2022-06-30
	2022-08-31
	…
	2024-04-30
	2024-07-01
	2024-09-03
	2024-10-31
	2024-12-31
]

# Portfolio Construction

In [17]:
rebalance_summary = run_rebalance_simulation(
    factor_reference_table=price_date_df,
    rebalance_allocation_df=rebalance_allocation_df,
    initial_capital=INITIAL_CAPITAL,
    rebalance_dates=rebalance_date,
    execution_cost_rate=EXECUTION_COST_RATE,
    commission_per_share=COMMISSION_PER_SHARE
)
rebalance_summary["rebalance_level_table"]

shape: (19, 5)
┌────────────────┬───────────────────────┬──────────────────────┬───────────────┬──────────────────┐
│ rebalance_date ┆ pre_rebalance_portfol ┆ post_rebalance_portf ┆ cash_residual ┆ transaction_cost │
│ ---            ┆ io_value              ┆ olio_value           ┆ ---           ┆ ---              │
│ date           ┆ ---                   ┆ ---                  ┆ f64           ┆ f64              │
│                ┆ f64                   ┆ f64                  ┆               ┆                  │
╞════════════════╪═══════════════════════╪══════════════════════╪═══════════════╪══════════════════╡
│ 2021-12-31     ┆ 1e6                   ┆ 998976.191123        ┆ 1137.314027   ┆ 1023.808877      │
│ 2022-02-28     ┆ 856221.430925         ┆ 854411.858909        ┆ -476.039922   ┆ 1809.572016      │
│ 2022-05-02     ┆ 927211.597011         ┆ 925607.882371        ┆ -63.733927    ┆ 1603.71464       │
│ 2022-06-30     ┆ 880665.677317         ┆ 879133.012236        ┆ -275.40509    ┆ 1532.665081      │
│ 2022-08-31     ┆ 999423.805348         ┆ 997711.873931        ┆ 127.361094    ┆ 1711.931417      │
│ …              ┆ …                     ┆ …                    ┆ …             ┆ …                │
│ 2024-04-30     ┆ 1.8367e6              ┆ 1.8332e6             ┆ -906.557785   ┆ 3454.984999      │
│ 2024-07-01     ┆ 1.9034e6              ┆ 1.9002e6             ┆ -777.462812   ┆ 3225.969912      │
│ 2024-09-03     ┆ 1.9190e6              ┆ 1.9149e6             ┆ -1450.29031   ┆ 4106.055004      │
│ 2024-10-31     ┆ 1.9966e6              ┆ 1.9932e6             ┆ 908.805957    ┆ 3379.919849      │
│ 2024-12-31     ┆ 1.9470e6              ┆ 1.9429e6             ┆ -1114.034184  ┆ 4089.379129      │
└────────────────┴───────────────────────┴──────────────────────┴───────────────┴──────────────────┘

In [18]:
rebalance_summary["position_level_table"]

shape: (190, 3)
┌────────────────┬────────┬────────┐
│ rebalance_date ┆ ticker ┆ shares │
│ ---            ┆ ---    ┆ ---    │
│ date           ┆ str    ┆ i64    │
╞════════════════╪════════╪════════╡
│ 2021-12-31     ┆ ALB    ┆ 451    │
│ 2021-12-31     ┆ AMD    ┆ 683    │
│ 2021-12-31     ┆ BLDR   ┆ 1185   │
│ 2021-12-31     ┆ COST   ┆ 186    │
│ 2021-12-31     ┆ DDOG   ┆ 557    │
│ …              ┆ …      ┆ …      │
│ 2024-12-31     ┆ NI     ┆ 5513   │
│ 2024-12-31     ┆ PLTR   ┆ 2507   │
│ 2024-12-31     ┆ TPL    ┆ 529    │
│ 2024-12-31     ┆ TRGP   ┆ 1127   │
│ 2024-12-31     ┆ UAL    ┆ 1988   │
└────────────────┴────────┴────────┘

In [19]:
rebalance_summary["trade_level_table"]

shape: (330, 9)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ rebalance_ ┆ ticker ┆ shares_tra ┆ rebalance ┆ … ┆ execution ┆ commissio ┆ transacti ┆ cash_flow │
│ date       ┆ ---    ┆ ded        ┆ _open     ┆   ┆ _cost     ┆ n         ┆ on_cost   ┆ s         │
│ ---        ┆ str    ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ date       ┆        ┆ i64        ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2021-12-31 ┆ ALB    ┆ 451        ┆ 221.23586 ┆ … ┆ 99.777374 ┆ 2.255     ┆ 102.03237 ┆ -99879.40 │
│            ┆        ┆            ┆ 2         ┆   ┆           ┆           ┆ 4         ┆ 6055      │
│ 2021-12-31 ┆ AMD    ┆ 683        ┆ 146.16000 ┆ … ┆ 99.827283 ┆ 3.415     ┆ 103.24228 ┆ -99930.52 │
│            ┆        ┆            ┆ 4         ┆   ┆           ┆           ┆ 3         ┆ 4784      │
│ 2021-12-31 ┆ BLDR   ┆ 1185       ┆ 84.290001 ┆ … ┆ 99.883651 ┆ 5.925     ┆ 105.80865 ┆ -99989.45 │
│            ┆        ┆            ┆           ┆   ┆           ┆           ┆ 1         ┆ 9736      │
│ 2021-12-31 ┆ COST   ┆ 186        ┆ 534.79194 ┆ … ┆ 99.471302 ┆ 0.93      ┆ 100.40130 ┆ -99571.70 │
│            ┆        ┆            ┆ 5         ┆   ┆           ┆           ┆ 2         ┆ 3122      │
│ 2021-12-31 ┆ DDOG   ┆ 557        ┆ 179.19000 ┆ … ┆ 99.808831 ┆ 2.785     ┆ 102.59383 ┆ -99911.42 │
│            ┆        ┆            ┆ 2         ┆   ┆           ┆           ┆ 1         ┆ 5191      │
│ …          ┆ …      ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2024-12-31 ┆ NI     ┆ 5513       ┆ 35.274594 ┆ … ┆ 194.46883 ┆ 27.565    ┆ 222.03383 ┆ -194690.8 │
│            ┆        ┆            ┆           ┆   ┆ 8         ┆           ┆ 8         ┆ 71738     │
│ 2024-12-31 ┆ PLTR   ┆ 2507       ┆ 77.580002 ┆ … ┆ 194.49306 ┆ 12.535    ┆ 207.02806 ┆ -194700.0 │
│            ┆        ┆            ┆           ┆   ┆ 5         ┆           ┆ 5         ┆ 92655     │
│ 2024-12-31 ┆ TPL    ┆ 529        ┆ 367.41918 ┆ … ┆ 194.36475 ┆ 2.645     ┆ 197.00975 ┆ -194561.7 │
│            ┆        ┆            ┆ 9         ┆   ┆ 1         ┆           ┆ 1         ┆ 6098      │
│ 2024-12-31 ┆ TRGP   ┆ 1127       ┆ 172.53897 ┆ … ┆ 194.45142 ┆ 5.635     ┆ 200.08642 ┆ -194651.5 │
│            ┆        ┆            ┆ 2         ┆   ┆ 2         ┆           ┆ 2         ┆ 08072     │
│ 2024-12-31 ┆ UAL    ┆ 1988       ┆ 97.82     ┆ … ┆ 194.46615 ┆ 9.94      ┆ 204.40615 ┆ -194670.5 │
│            ┆        ┆            ┆           ┆   ┆ 9         ┆           ┆ 9         ┆ 65553     │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# Portfolio Valuation

In [20]:
rebalance_period_close_prices = get_backtest_period_close_prices(
    cleaned_close_prices_dataset=close_price,
    backtest_start_date=BACKTEST_START_DATE,
    backtest_end_date=end_date,
)
rebalance_period_close_prices

shape: (379_262, 3)
┌────────────┬────────┬────────────┐
│ date       ┆ ticker ┆ close      │
│ ---        ┆ ---    ┆ ---        │
│ date       ┆ str    ┆ f64        │
╞════════════╪════════╪════════════╡
│ 2021-12-31 ┆ A      ┆ 154.27504  │
│ 2021-12-31 ┆ AAPL   ┆ 173.599014 │
│ 2021-12-31 ┆ ABBV   ┆ 114.065155 │
│ 2021-12-31 ┆ ABNB   ┆ 166.490005 │
│ 2021-12-31 ┆ ABT    ┆ 128.19101  │
│ …          ┆ …      ┆ …          │
│ 2024-12-31 ┆ XYZ    ┆ 84.989998  │
│ 2024-12-31 ┆ YUM    ┆ 130.370239 │
│ 2024-12-31 ┆ ZBH    ┆ 104.037064 │
│ 2024-12-31 ┆ ZBRA   ┆ 386.220001 │
│ 2024-12-31 ┆ ZTS    ┆ 158.312546 │
└────────────┴────────┴────────────┘

In [21]:
next_date_matched_rebalance_level_table = get_next_date_matched_rebalance_level_table(
    rebalance_level_table=rebalance_summary["rebalance_level_table"]
)
next_date_matched_rebalance_level_table

shape: (19, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ rebalance_date ┆ pre_rebalance_ ┆ post_rebalance ┆ cash_residual ┆ transaction_c ┆ next_rebalanc │
│ ---            ┆ portfolio_valu ┆ _portfolio_val ┆ ---           ┆ ost           ┆ e_date        │
│ date           ┆ e              ┆ ue             ┆ f64           ┆ ---           ┆ ---           │
│                ┆ ---            ┆ ---            ┆               ┆ f64           ┆ date          │
│                ┆ f64            ┆ f64            ┆               ┆               ┆               │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 2021-12-31     ┆ 1e6            ┆ 998976.191123  ┆ 1137.314027   ┆ 1023.808877   ┆ 2022-02-28    │
│ 2022-02-28     ┆ 856221.430925  ┆ 854411.858909  ┆ -476.039922   ┆ 1809.572016   ┆ 2022-05-02    │
│ 2022-05-02     ┆ 927211.597011  ┆ 925607.882371  ┆ -63.733927    ┆ 1603.71464    ┆ 2022-06-30    │
│ 2022-06-30     ┆ 880665.677317  ┆ 879133.012236  ┆ -275.40509    ┆ 1532.665081   ┆ 2022-08-31    │
│ 2022-08-31     ┆ 999423.805348  ┆ 997711.873931  ┆ 127.361094    ┆ 1711.931417   ┆ 2022-10-31    │
│ …              ┆ …              ┆ …              ┆ …             ┆ …             ┆ …             │
│ 2024-04-30     ┆ 1.8367e6       ┆ 1.8332e6       ┆ -906.557785   ┆ 3454.984999   ┆ 2024-07-01    │
│ 2024-07-01     ┆ 1.9034e6       ┆ 1.9002e6       ┆ -777.462812   ┆ 3225.969912   ┆ 2024-09-03    │
│ 2024-09-03     ┆ 1.9190e6       ┆ 1.9149e6       ┆ -1450.29031   ┆ 4106.055004   ┆ 2024-10-31    │
│ 2024-10-31     ┆ 1.9966e6       ┆ 1.9932e6       ┆ 908.805957    ┆ 3379.919849   ┆ 2024-12-31    │
│ 2024-12-31     ┆ 1.9470e6       ┆ 1.9429e6       ┆ -1114.034184  ┆ 4089.379129   ┆ null          │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [22]:
daily_position_value_table = get_daily_position_value_table(
    backtest_period_close_prices=rebalance_period_close_prices,
    next_date_matched_rebalance_level_table=next_date_matched_rebalance_level_table,
    position_level_table=rebalance_summary["position_level_table"],
)
daily_position_value_table

shape: (7_540, 6)
┌────────────┬────────────────┬────────┬────────┬────────────┬────────────────┐
│ date       ┆ rebalance_date ┆ ticker ┆ shares ┆ close      ┆ position_value │
│ ---        ┆ ---            ┆ ---    ┆ ---    ┆ ---        ┆ ---            │
│ date       ┆ date           ┆ str    ┆ i64    ┆ f64        ┆ f64            │
╞════════════╪════════════════╪════════╪════════╪════════════╪════════════════╡
│ 2021-12-31 ┆ 2021-12-31     ┆ ALB    ┆ 451    ┆ 221.008972 ┆ 99675.046448   │
│ 2021-12-31 ┆ 2021-12-31     ┆ AMD    ┆ 683    ┆ 143.899994 ┆ 98283.695831   │
│ 2021-12-31 ┆ 2021-12-31     ┆ BLDR   ┆ 1185   ┆ 85.709999  ┆ 101566.348915  │
│ 2021-12-31 ┆ 2021-12-31     ┆ COST   ┆ 186    ┆ 538.864075 ┆ 100228.717896  │
│ 2021-12-31 ┆ 2021-12-31     ┆ DDOG   ┆ 557    ┆ 178.110001 ┆ 99207.27034    │
│ …          ┆ …              ┆ …      ┆ …      ┆ …          ┆ …              │
│ 2024-12-31 ┆ 2024-12-31     ┆ NI     ┆ 5513   ┆ 35.284191  ┆ 194521.745708  │
│ 2024-12-31 ┆ 2024-12-31     ┆ PLTR   ┆ 2507   ┆ 75.629997  ┆ 189604.403114  │
│ 2024-12-31 ┆ 2024-12-31     ┆ TPL    ┆ 529    ┆ 365.423492 ┆ 193309.027496  │
│ 2024-12-31 ┆ 2024-12-31     ┆ TRGP   ┆ 1127   ┆ 172.897354 ┆ 194855.3181    │
│ 2024-12-31 ┆ 2024-12-31     ┆ UAL    ┆ 1988   ┆ 97.099998  ┆ 193034.796967  │
└────────────┴────────────────┴────────┴────────┴────────────┴────────────────┘

In [23]:
daily_portfolio_table = get_daily_portfolio_table(
    next_date_matched_rebalance_level_table=next_date_matched_rebalance_level_table,
    daily_position_value_table=daily_position_value_table,
    initial_capital=INITIAL_CAPITAL
)
daily_portfolio_table

shape: (754, 5)
┌────────────┬─────────────────┬───────────────┬─────────────────┬──────────────┐
│ date       ┆ positions_value ┆ cash_residual ┆ portfolio_value ┆ daily_return │
│ ---        ┆ ---             ┆ ---           ┆ ---             ┆ ---          │
│ date       ┆ f64             ┆ f64           ┆ f64             ┆ f64          │
╞════════════╪═════════════════╪═══════════════╪═════════════════╪══════════════╡
│ 2021-12-31 ┆ 999775.987938   ┆ 1137.314027   ┆ 1.0009e6        ┆ 0.000913     │
│ 2022-01-03 ┆ 984317.072136   ┆ 1137.314027   ┆ 985454.386163   ┆ -0.015445    │
│ 2022-01-04 ┆ 979994.58197    ┆ 1137.314027   ┆ 981131.895998   ┆ -0.004386    │
│ 2022-01-05 ┆ 939071.453529   ┆ 1137.314027   ┆ 940208.767557   ┆ -0.04171     │
│ 2022-01-06 ┆ 936567.684242   ┆ 1137.314027   ┆ 937704.99827    ┆ -0.002663    │
│ …          ┆ …               ┆ …             ┆ …               ┆ …            │
│ 2024-12-24 ┆ 1.9756e6        ┆ 908.805957    ┆ 1.9765e6        ┆ 0.006458     │
│ 2024-12-26 ┆ 1.9718e6        ┆ 908.805957    ┆ 1.9728e6        ┆ -0.001911    │
│ 2024-12-27 ┆ 1.9560e6        ┆ 908.805957    ┆ 1.9569e6        ┆ -0.008037    │
│ 2024-12-30 ┆ 1.9394e6        ┆ 908.805957    ┆ 1.9403e6        ┆ -0.008472    │
│ 2024-12-31 ┆ 1.9266e6        ┆ -1114.034184  ┆ 1.9255e6        ┆ -0.00766     │
└────────────┴─────────────────┴───────────────┴─────────────────┴──────────────┘

# Analytics

## Return metrics

In [24]:
daily_portfolio_value_return_df = prepare_daily_portfolio_value_return_df(
    daily_portfolio_table=daily_portfolio_table
)
daily_portfolio_value_return_df

shape: (754, 3)
┌────────────┬─────────────────┬──────────────┐
│ date       ┆ portfolio_value ┆ daily_return │
│ ---        ┆ ---             ┆ ---          │
│ date       ┆ f64             ┆ f64          │
╞════════════╪═════════════════╪══════════════╡
│ 2021-12-31 ┆ 1.0009e6        ┆ 0.000913     │
│ 2022-01-03 ┆ 985454.386163   ┆ -0.015445    │
│ 2022-01-04 ┆ 981131.895998   ┆ -0.004386    │
│ 2022-01-05 ┆ 940208.767557   ┆ -0.04171     │
│ 2022-01-06 ┆ 937704.99827    ┆ -0.002663    │
│ …          ┆ …               ┆ …            │
│ 2024-12-24 ┆ 1.9765e6        ┆ 0.006458     │
│ 2024-12-26 ┆ 1.9728e6        ┆ -0.001911    │
│ 2024-12-27 ┆ 1.9569e6        ┆ -0.008037    │
│ 2024-12-30 ┆ 1.9403e6        ┆ -0.008472    │
│ 2024-12-31 ┆ 1.9255e6        ┆ -0.00766     │
└────────────┴─────────────────┴──────────────┘

In [25]:
total_return = calculate_total_return(
    daily_portfolio_value_return_df=daily_portfolio_value_return_df,
    initial_capital=INITIAL_CAPITAL
)
total_return

0.9254577012935494

In [26]:
annualized_return_cagr = calculate_annualized_return_cagr(
    daily_portfolio_value_return_df=daily_portfolio_value_return_df,
    initial_capital=INITIAL_CAPITAL
)
annualized_return_cagr

0.24515245153343113

In [27]:
mean_daily_return = calculate_mean_daily_return(
    daily_portfolio_value_return_df=daily_portfolio_value_return_df
)
mean_daily_return

0.0009971295784436524

In [28]:
annualized_mean_daily_return = calculate_annualized_mean_return(
    daily_portfolio_value_return_df=daily_portfolio_value_return_df
)
annualized_mean_daily_return

0.28550477123025475

## Risk metrics

In [29]:
mean_daily_std = calculate_daily_return_std(
    daily_portfolio_value_return_df=daily_portfolio_value_return_df
)
mean_daily_std

0.015985802023062733

In [30]:
annualized_volatility = calculate_annualized_volatility(
    daily_portfolio_value_return_df=daily_portfolio_value_return_df
)
annualized_volatility

0.25376673996562327

In [31]:
drawdown = calculate_drawdown(
    daily_portfolio_value_return_df=daily_portfolio_value_return_df
)
drawdown

shape: (754, 4)
┌────────────┬─────────────────┬──────────────┬───────────┐
│ date       ┆ portfolio_value ┆ daily_return ┆ drawdown  │
│ ---        ┆ ---             ┆ ---          ┆ ---       │
│ date       ┆ f64             ┆ f64          ┆ f64       │
╞════════════╪═════════════════╪══════════════╪═══════════╡
│ 2021-12-31 ┆ 1.0009e6        ┆ 0.000913     ┆ 0.0       │
│ 2022-01-03 ┆ 985454.386163   ┆ -0.015445    ┆ -0.015445 │
│ 2022-01-04 ┆ 981131.895998   ┆ -0.004386    ┆ -0.019763 │
│ 2022-01-05 ┆ 940208.767557   ┆ -0.04171     ┆ -0.060649 │
│ 2022-01-06 ┆ 937704.99827    ┆ -0.002663    ┆ -0.063151 │
│ …          ┆ …               ┆ …            ┆ …         │
│ 2024-12-24 ┆ 1.9765e6        ┆ 0.006458     ┆ -0.070752 │
│ 2024-12-26 ┆ 1.9728e6        ┆ -0.001911    ┆ -0.072527 │
│ 2024-12-27 ┆ 1.9569e6        ┆ -0.008037    ┆ -0.079981 │
│ 2024-12-30 ┆ 1.9403e6        ┆ -0.008472    ┆ -0.087775 │
│ 2024-12-31 ┆ 1.9255e6        ┆ -0.00766     ┆ -0.094763 │
└────────────┴─────────────────┴──────────────┴───────────┘

In [32]:
max_drawdown = calculate_max_drawdown(drawdown_table=drawdown)
max_drawdown

-0.20134209990266316

In [33]:
sharpe_ratio = calculate_sharpe_ratio(
    mean_daily_return=mean_daily_return, annualized_volatility=annualized_volatility, annual_rf=ANNUAL_RISK_FREE_RATE
)
sharpe_ratio

0.8719686977015815

In [34]:
calmer_ratio = calculate_calmer_ratio(
    annualized_return_cagr=annualized_return_cagr, max_drawdown=max_drawdown
)
calmer_ratio

1.2175916097624275

In [35]:
sortino_ratio = calculate_sortino_ratio(
    daily_portfolio_value_return_df=daily_portfolio_value_return_df,
    mean_daily_return=mean_daily_return,
    annual_rf=ANNUAL_RISK_FREE_RATE
)
sortino_ratio

1.2537348745146693

## Turnover metrics

In [36]:
portfolio_turnover_table = get_portfolio_turnover_table(
    rebalance_level_table=rebalance_summary["rebalance_level_table"],
    trade_level_table=rebalance_summary["trade_level_table"],
)
portfolio_turnover_table

shape: (19, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ rebalance ┆ buy_value ┆ sell_valu ┆ pre_rebal ┆ … ┆ cash_resi ┆ transacti ┆ one_way_t ┆ transact │
│ _date     ┆ ---       ┆ e         ┆ ance_port ┆   ┆ dual      ┆ on_cost   ┆ urnover   ┆ ion_cost │
│ ---       ┆ f64       ┆ ---       ┆ folio_val ┆   ┆ ---       ┆ ---       ┆ ---       ┆ _ratio   │
│ date      ┆           ┆ f64       ┆ ue        ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆ ---       ┆   ┆           ┆           ┆           ┆ f64      │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2021-12-3 ┆ 997838.87 ┆ 0.0       ┆ 1e6       ┆ … ┆ 1137.3140 ┆ 1023.8088 ┆ 1.0       ┆ 0.001024 │
│ 1         ┆ 7096      ┆           ┆           ┆   ┆ 27        ┆ 77        ┆           ┆          │
│ 2022-02-2 ┆ 854887.89 ┆ 855084.11 ┆ 856221.43 ┆ … ┆ -476.0399 ┆ 1809.5720 ┆ 0.998443  ┆ 0.002113 │
│ 8         ┆ 8831      ┆ 6898      ┆ 0925      ┆   ┆ 22        ┆ 16        ┆           ┆          │
│ 2022-05-0 ┆ 740541.80 ┆ 742557.83 ┆ 927211.59 ┆ … ┆ -63.73392 ┆ 1603.7146 ┆ 0.798676  ┆ 0.00173  │
│ 2         ┆ 9826      ┆ 0461      ┆ 7011      ┆   ┆ 7         ┆ 4         ┆           ┆          │
│ 2022-06-3 ┆ 707104.54 ┆ 708425.53 ┆ 880665.67 ┆ … ┆ -275.4050 ┆ 1532.6650 ┆ 0.802921  ┆ 0.00174  │
│ 0         ┆ 3345      ┆ 7263      ┆ 7317      ┆   ┆ 9         ┆ 81        ┆           ┆          │
│ 2022-08-3 ┆ 797995.85 ┆ 800110.55 ┆ 999423.80 ┆ … ┆ 127.36109 ┆ 1711.9314 ┆ 0.798456  ┆ 0.001713 │
│ 1         ┆ 9796      ┆ 7397      ┆ 5348      ┆   ┆ 4         ┆ 17        ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2024-04-3 ┆ 1.6507e6  ┆ 1.6536e6  ┆ 1.8367e6  ┆ … ┆ -906.5577 ┆ 3454.9849 ┆ 0.898741  ┆ 0.001881 │
│ 0         ┆           ┆           ┆           ┆   ┆ 85        ┆ 99        ┆           ┆          │
│ 2024-07-0 ┆ 1.5307e6  ┆ 1.5340e6  ┆ 1.9034e6  ┆ … ┆ -777.4628 ┆ 3225.9699 ┆ 0.804184  ┆ 0.001695 │
│ 1         ┆           ┆           ┆           ┆   ┆ 12        ┆ 12        ┆           ┆          │
│ 2024-09-0 ┆ 1.9164e6  ┆ 1.9198e6  ┆ 1.9190e6  ┆ … ┆ -1450.290 ┆ 4106.0550 ┆ 0.998616  ┆ 0.00214  │
│ 3         ┆           ┆           ┆           ┆   ┆ 31        ┆ 04        ┆           ┆          │
│ 2024-10-3 ┆ 1.5959e6  ┆ 1.6017e6  ┆ 1.9966e6  ┆ … ┆ 908.80595 ┆ 3379.9198 ┆ 0.799336  ┆ 0.001693 │
│ 1         ┆           ┆           ┆           ┆   ┆ 7         ┆ 49        ┆           ┆          │
│ 2024-12-3 ┆ 1.9441e6  ┆ 1.9461e6  ┆ 1.9470e6  ┆ … ┆ -1114.034 ┆ 4089.3791 ┆ 0.998472  ┆ 0.0021   │
│ 1         ┆           ┆           ┆           ┆   ┆ 184       ┆ 29        ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [37]:
average_turnover = calculate_average_turnover(
    portfolio_turnover_table=portfolio_turnover_table
)
average_turnover

0.7805819674254958

In [38]:
annualized_turnover = calculate_annualized_turnover(
    portfolio_turnover_table=portfolio_turnover_table,
    rebalance_frequency=REBALANCE_FREQUENCY,
    rebalance_freq_unit=REBALANCE_FREQ_UNIT,
)
annualized_turnover

4.6834918045529745

In [39]:
total_transaction_cost = calculate_total_transaction_cost(
    portfolio_turnover_table=portfolio_turnover_table
)
total_transaction_cost

43047.26439354556

In [40]:
total_transaction_cost_to_initial_cap = calculate_total_transaction_cost_ratio(
    portfolio_turnover_table=portfolio_turnover_table, initial_capital=INITIAL_CAPITAL
)
total_transaction_cost_to_initial_cap

0.043047264393545566

In [41]:
average_transaction_cost_ratio = calculate_average_transaction_cost_ratio(
    portfolio_turnover_table=portfolio_turnover_table
)
average_transaction_cost_ratio

0.0016413871560434514

## Benchmark metrics

In [42]:
daily_benchmark_table = get_daily_benchmark_table(
    benchmark_data=benchmark_data,
    benchmark_ticker=BENCHMARK_TICKER,
    backtest_start_date=BACKTEST_START_DATE,
    backtest_end_date=end_date,
)
daily_benchmark_table

shape: (754, 5)
┌────────────┬────────┬─────────────┬─────────────┬──────────────┐
│ date       ┆ ticker ┆ open        ┆ close       ┆ daily_return │
│ ---        ┆ ---    ┆ ---         ┆ ---         ┆ ---          │
│ date       ┆ str    ┆ f64         ┆ f64         ┆ f64          │
╞════════════╪════════╪═════════════╪═════════════╪══════════════╡
│ 2021-12-31 ┆ ^GSPC  ┆ 4775.209961 ┆ 4766.180176 ┆ -0.001891    │
│ 2022-01-03 ┆ ^GSPC  ┆ 4778.140137 ┆ 4796.560059 ┆ 0.006374     │
│ 2022-01-04 ┆ ^GSPC  ┆ 4804.509766 ┆ 4793.540039 ┆ -0.00063     │
│ 2022-01-05 ┆ ^GSPC  ┆ 4787.990234 ┆ 4700.580078 ┆ -0.019393    │
│ 2022-01-06 ┆ ^GSPC  ┆ 4693.390137 ┆ 4696.049805 ┆ -0.000964    │
│ …          ┆ …      ┆ …           ┆ …           ┆ …            │
│ 2024-12-24 ┆ ^GSPC  ┆ 5984.629883 ┆ 6040.040039 ┆ 0.011043     │
│ 2024-12-26 ┆ ^GSPC  ┆ 6024.970215 ┆ 6037.589844 ┆ -0.000406    │
│ 2024-12-27 ┆ ^GSPC  ┆ 6006.169922 ┆ 5970.839844 ┆ -0.011056    │
│ 2024-12-30 ┆ ^GSPC  ┆ 5920.669922 ┆ 5906.939941 ┆ -0.010702    │
│ 2024-12-31 ┆ ^GSPC  ┆ 5919.740234 ┆ 5881.629883 ┆ -0.004285    │
└────────────┴────────┴─────────────┴─────────────┴──────────────┘

In [43]:
portfolio_benchmark_returns_table = get_portfolio_benchmark_returns_table(
    daily_benchmark_table=daily_benchmark_table,
    daily_portfolio_value_return_df=daily_portfolio_value_return_df
)
portfolio_benchmark_returns_table

shape: (754, 3)
┌────────────┬──────────────────┬──────────────────┐
│ date       ┆ portfolio_return ┆ benchmark_return │
│ ---        ┆ ---              ┆ ---              │
│ date       ┆ f64              ┆ f64              │
╞════════════╪══════════════════╪══════════════════╡
│ 2021-12-31 ┆ 0.000913         ┆ -0.001891        │
│ 2022-01-03 ┆ -0.015445        ┆ 0.006374         │
│ 2022-01-04 ┆ -0.004386        ┆ -0.00063         │
│ 2022-01-05 ┆ -0.04171         ┆ -0.019393        │
│ 2022-01-06 ┆ -0.002663        ┆ -0.000964        │
│ …          ┆ …                ┆ …                │
│ 2024-12-24 ┆ 0.006458         ┆ 0.011043         │
│ 2024-12-26 ┆ -0.001911        ┆ -0.000406        │
│ 2024-12-27 ┆ -0.008037        ┆ -0.011056        │
│ 2024-12-30 ┆ -0.008472        ┆ -0.010702        │
│ 2024-12-31 ┆ -0.00766         ┆ -0.004285        │
└────────────┴──────────────────┴──────────────────┘

In [44]:
portfolio_beta = calculate_portfolio_beta(
    portfolio_benchmark_returns_table=portfolio_benchmark_returns_table
)
portfolio_beta

0.8871682871367964

In [45]:
jensens_alpha = calculate_jensens_alpha(
    portfolio_benchmark_returns_table=portfolio_benchmark_returns_table,
    portfolio_beta=portfolio_beta,
    annual_rf=ANNUAL_RISK_FREE_RATE,
)
jensens_alpha

0.17259177375799312

In [46]:
r_squared = calculate_r_squared(
    portfolio_benchmark_returns_table=portfolio_benchmark_returns_table
)
r_squared

0.3734276273449216

In [47]:
annualized_tracking_error = calculate_annualized_tracking_error(
    portfolio_benchmark_returns_table=portfolio_benchmark_returns_table
)
annualized_tracking_error

0.20183832623279596

In [48]:
information_ratio = calculate_information_ratio(
    portfolio_benchmark_returns_table=portfolio_benchmark_returns_table
)
information_ratio

0.8241450046051636

In [49]:
treynor_ratio = calculate_treynor_ratio(
    daily_portfolio_value_return_df=daily_portfolio_value_return_df,
    portfolio_beta=portfolio_beta,
    annual_rf=ANNUAL_RISK_FREE_RATE,
)
treynor_ratio

0.24991438613870542

In [50]:
best_day = get_best_day(daily_portfolio_value_return_df=daily_portfolio_value_return_df)
best_day

shape: (1, 3)
┌────────────┬─────────────────┬──────────────┐
│ date       ┆ portfolio_value ┆ daily_return │
│ ---        ┆ ---             ┆ ---          │
│ date       ┆ f64             ┆ f64          │
╞════════════╪═════════════════╪══════════════╡
│ 2024-07-31 ┆ 1.8210e6        ┆ 0.055243     │
└────────────┴─────────────────┴──────────────┘

In [51]:
worst_day = get_worst_day(daily_portfolio_value_return_df=daily_portfolio_value_return_df)
worst_day

shape: (1, 3)
┌────────────┬─────────────────┬──────────────┐
│ date       ┆ portfolio_value ┆ daily_return │
│ ---        ┆ ---             ┆ ---          │
│ date       ┆ f64             ┆ f64          │
╞════════════╪═════════════════╪══════════════╡
│ 2024-07-24 ┆ 1.7667e6        ┆ -0.064914    │
└────────────┴─────────────────┴──────────────┘

In [52]:
win_rate = get_win_rate(
    daily_portfolio_value_return_df=daily_portfolio_value_return_df
)
win_rate

0.5464190981432361